### ISSUE TITLE
About the metric on Tracffic BJ? 

### ISSUE THREAD

**Issue by toddwyl** [JeremDona/spatiotemporal_variable_separation#2]
The shape of data in dataset Traffic BJ is 2 channels. (shape: [B, 2, 32, 32])
The mse in Traffic BJ are the mean of channels or the sum of the channels ?
Because I noticed that the code in repo is written as below:
https://github.com/JeremDona/spatiotemporal_variable_separation/blob/3f5e0417d7da5ad6bc5261a5c900760a886236b5/var_sep/test/taxibj/test.py#L52

**Comment by JeremieDona** [comment]
Hi! Thank you for your interest in our work.

Indeed, we compute in this test code the mean squared error by averaging over all dimensions.

To retrieve the results presented in the paper, we multiply the computed metric by a hundred times the dimension of the image, i.e. 100x32x32x2, which amounts to summing over the image dimensions.
