### ISSUE TITLE
About SST dataset?

### ISSUE THREAD

**Issue by toddwyl** [JeremDona/spatiotemporal_variable_separation#3]
Would it be possible for you to send me the **SST** dataset which mentioned in the paper?
I download in the website which is nc file.
After preprocessing as the paper, I cannot get the seq in the paper.
I would appreciate it if you could send me as soon as possible.
Thank you in advance!
My Email is strawsuper@gmail.com

**Comment by White-Link** [comment]
Hi, we just sent you a mail!

**Comment by toddwyl** [comment]
> Hi, we just sent you a mail!

Thanks a lot!

**Comment by fanshuhuangjia** [comment]
> Hi, we just sent you a mail!

Will it be convenient for you to send me the **SST** datasets which mentioned in the paper?
I also find it difficult to get the datasets following the introduction in the paper.
Thank you in advance for your kind help and I am looking forward to your reply.
My email is : 201050044@hdu.edu.cn

**Comment by White-Link** [comment]
Hi, we just sent you a mail about the SST dataset.

Regarding the other datasets, what is the issue that you encounter? Besides our paper, you can find more details about the datasets that we used [in the README of this repository](https://github.com/JeremDona/spatiotemporal_variable_separation#datasets).

**Comment by fanshuhuangjia** [comment]
> Hi, we just sent you a mail about the SST dataset.
> 
> Regarding the other datasets, what is the issue that you encounter? Besides our paper, you can find more details about the datasets that we used [in the README of this repository](https://github.com/JeremDona/spatiotemporal_variable_separation#datasets).

Thank you very much for your helping.
I'm sorry to have failed to make myself clear. What I really want to express is that I got the same problem with ManWingloeng.
There is no issue regard to other datasets. Your instructions are detailed enough to got them~
Thanks again!
