### ISSUE TITLE
Some questions about the results on SST dataset

### ISSUE THREAD

**Issue by fanshuhuangjia** [JeremDona/spatiotemporal_variable_separation#4]
Hi, this is great work, and it is very helpful to my current research. I just have a subtle question about the results on the SST datasets . I find the results reported by [PhyDNet](https://openaccess.thecvf.com/content_CVPR_2020/papers/Le_Guen_Disentangling_Physical_Dynamics_From_Unknown_Factors_for_Unsupervised_Video_Prediction_CVPR_2020_paper.pdf) are so great (for example the SSIM reach 0.972).
![微信截图_20210913192512](https://user-images.githubusercontent.com/69073478/133075458-449bdd43-d43e-412e-9a9e-462245a5cca3.png)
But it's so different from the results reported in this paper while the description of datasets are equal. 
![微信截图_20210913192601](https://user-images.githubusercontent.com/69073478/133075720-cab80919-01d0-4703-92e5-e3c32604afac.png)
So, will it be convenient for you to tell me what makes the difference between the two papers?
Thank you in advance for your kind help and I am looking forward to your reply.

**Comment by JeremieDona** [comment]
Hi,

In fact the datasets differ, as we use the one described by [de Bezenac et al](https://arxiv.org/pdf/1711.07970.pdf) (with the same train and test split), and an update in the API to retrieve the data has seen a major update making the data we use unavailable without requesting them. Thus, PhyDNet in the original paper uses a different dataset for SST.


We also believe that a major difference occurs in the computation of the SSIM. You can see in this [file](https://github.com/JeremDona/spatiotemporal_variable_separation/blob/master/var_sep/test/sst/test.py) that we renormalize the data between 0 and 1 before computing the SSIM.
We believe that the normalization is different in the original PhyDNet paper, leading to substantial differences.

To compare both models in a fair manner, we trained both models on our version of the dataset and used the same "normalized" SSIM computation.

This explains the differences in the metrics between the two papers.

**Comment by fanshuhuangjia** [comment]
Thanks very much for solving my puzzle. : )
