### ISSUE TITLE
ODE resolution scheme

### ISSUE THREAD

**Issue by linkenghong** [JeremDona/spatiotemporal_variable_separation#5]
Hi, thanks for sharing this code, and the work is great. I just have a subtle question about the ODE resolution scheme. In the paper, it said that f is implemented by a neural network, and equation (7) is solved with an ODE resolution scheme like Chen et al. (2018). However, in the code, the solution of ODE is using Euler's method. Is my understanding wrong?

**Comment by White-Link** [comment]
Hi, thank you for your interest in our work!

Indeed, like Chen et al. (2018), we use neural-parameterized ODEs solved by an ODE solver of our choice. For practical reasons, we chose to implement this using the Euler resolution method, as specified in our architecture description of Section E.2.2 (paragraph "ODE solver").

Therefore, your understanding from the paper and the code is correct. Euler-solved neural-parameterized ODEs are an instance of Neural ODEs :slightly_smiling_face: 

Please let us know whether you have any other question!

**Comment by linkenghong** [comment]
Thank you.
